"""auto

Revision ID: eeb007892bfa
Revises: e356d3b04e6f
Create Date: 2025-09-09 09:08:12.518184+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb007892bfa'
down_revision: Union[str, None] = 'e356d3b04e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'candidate_cvs', ['id'])
    op.create_unique_constraint(None, 'cv_entries', ['id'])
    op.create_unique_constraint(None, 'cv_skills', ['id'])
    op.create_unique_constraint(None, 'job_descriptions', ['id'])
    op.create_unique_constraint(None, 'job_skills', ['id'])
    op.create_unique_constraint(None, 'session_states', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'session_states', type_='unique')
    op.drop_constraint(None, 'job_skills', type_='unique')
    op.drop_constraint(None, 'job_descriptions', type_='unique')
    op.drop_constraint(None, 'cv_skills', type_='unique')
    op.drop_constraint(None, 'cv_entries', type_='unique')
    op.drop_constraint(None, 'candidate_cvs', type_='unique')
    # ### end Alembic commands ###
